/**
 * Dedicated coverage tests for QSyncDocsTool private methods.
 *
 * Testing strategy: access private methods via `(tool as any).method()` to
 * avoid polluting the global module registry with `mock.module()`.
 * This covers all uncovered branches WITHOUT causing cross-file contamination.
 *
 * Covered:
 *   - generateToolMd (lines 123-154): HTML escaping, schema shape iteration
 *   - generateTransformerMd (lines 165-180): table generation, sorting
 *   - writeDoc (lines 191-194): mkdirSync + writeFileSync + push
 *   - injectDoc (lines 205-229):
 *       Branch A — file not found → skip
 *       Branch B — file found, no marker → append
 *       Branch C — file found, marker present → replace
 */
import { describe, it, expect, mock } from 'bun:test';
import { z } from 'zod';
import { QSyncDocsTool } from '../../../../src/mcp/tools/internal/sync-docs.tool';

function makeFs(options: {
	existsResult?: boolean | ((path: string) => boolean);
	readResult?: string | ((path: string) => string);
}) {
	const existsSync = mock((path: unknown) => {
		const res = options.existsResult ?? true;
		return typeof res === 'function' ? res(String(path)) : res;
	});
	const readFileSync = mock((path: unknown) => {
		const res = options.readResult ?? '';
		return typeof res === 'function' ? res(String(path)) : res;
	});
	const writeFileSync = mock(() => undefined);
	const mkdirSync = mock(() => undefined);
	return { existsSync, readFileSync, writeFileSync, mkdirSync };
}

function makeTool(fsOpts: Parameters<typeof makeFs>[0] = {}) {
	const tool = new QSyncDocsTool();
	const mockFs = makeFs(fsOpts);
	(tool as any)._fs = mockFs;
	return { tool, mockFs };
}

describe('QSyncDocsTool – metadata', () => {
	it('has correct name, description, and schema', () => {
		const tool = new QSyncDocsTool();
		expect(tool.name).toBe('update_docs_content');
		expect(typeof tool.description).toBe('string');
		expect(tool.description.length).toBeGreaterThan(0);
		expect(tool.schema).toBeDefined();
	});
});

describe('QSyncDocsTool – generateToolMd', () => {
	it('escapes HTML special characters in tool description', () => {
		const { tool } = makeTool();
		const tools = [
			{
				name: 'xss_tool',
				description: 'A <b>tool</b> with "quotes" & \'single\' chars',
				schema: z.object({}),
			},
		];
		const result = (tool as any).generateToolMd(tools, 'Generated by test');
		expect(result).toContain('&lt;b&gt;');
		expect(result).toContain('&quot;');
		expect(result).toContain('&#039;');
		expect(result).toContain('&amp;');
		expect(result).not.toContain('<b>');
	});

	it('generates ## heading for each tool', () => {
		const { tool } = makeTool();
		const tools = [
			{ name: 'tool_one', description: 'First', schema: z.object({}) },
			{ name: 'tool_two', description: 'Second', schema: z.object({}) },
		];
		const result = (tool as any).generateToolMd(tools, 'gen');
		expect(result).toContain('## `tool_one`');
		expect(result).toContain('## `tool_two`');
	});

	it('includes JSON schema for tools with parameters', () => {
		const { tool } = makeTool();
		const tools = [
			{
				name: 'parameterized_tool',
				description: 'Has params',
				schema: z.object({
					input: z.string().describe('The input string'),
					count: z.number().optional().describe('How many'),
				}),
			},
		];
		const result = (tool as any).generateToolMd(tools, 'gen');
		expect(result).toContain('input');
		expect(result).toContain('The input string');
		expect(result).toContain('```json');
	});

	it('includes the generatedBy comment', () => {
		const { tool } = makeTool();
		const result = (tool as any).generateToolMd(
			[],
			'Auto-generated by QuickModel'
		);
		expect(result).toContain('<!-- Auto-generated by QuickModel -->');
	});
});

describe('QSyncDocsTool – generateTransformerMd', () => {
	it('generates a markdown table with sorted transformer names', () => {
		const { tool } = makeTool();
		const transformers = ['date', 'number', 'string', 'boolean'];
		const texts = {
			transformersTitle: 'Transformers',
			transformersDesc: 'Available transformers.',
			generatedBy: 'Generated',
			transformerHeader: 'Name',
			descHeader: 'Description',
			customTransformers: 'You can also register custom transformers.',
		};
		const result = (tool as any).generateTransformerMd(transformers, texts);
		expect(result).toContain('| Name | Description |');
		const boolIdx = result.indexOf('`boolean`');
		const dateIdx = result.indexOf('`date`');
		const numIdx = result.indexOf('`number`');
		const strIdx = result.indexOf('`string`');
		expect(boolIdx).toBeLessThan(dateIdx);
		expect(dateIdx).toBeLessThan(numIdx);
		expect(numIdx).toBeLessThan(strIdx);
	});

	it('includes the title, description, and custom footer', () => {
		const { tool } = makeTool();
		const texts = {
			transformersTitle: 'My Transformers',
			transformersDesc: 'Use them wisely.',
			generatedBy: 'QSyncDocsTool',
			transformerHeader: 'Transformer',
			descHeader: 'Detail',
			customTransformers: 'Add your own transformers.',
		};
		const result = (tool as any).generateTransformerMd(['date'], texts);
		expect(result).toContain('# My Transformers');
		expect(result).toContain('Use them wisely.');
		expect(result).toContain('<!-- QSyncDocsTool -->');
		expect(result).toContain('Add your own transformers.');
	});
});

describe('QSyncDocsTool – writeDoc', () => {
	it('calls mkdirSync, writeFileSync, and pushes path', () => {
		const { tool, mockFs } = makeTool();
		const updatedFiles: string[] = [];
		const docPath = '/project/docs/en/guide/transformers.md';
		const content = '# Transformers\n\nContent here.';
		(tool as any).writeDoc(docPath, content, updatedFiles);
		expect(mockFs.mkdirSync).toHaveBeenCalledTimes(1);
		expect(mockFs.writeFileSync).toHaveBeenCalledWith(docPath, content);
		expect(updatedFiles).toContain(docPath);
	});
});

describe('QSyncDocsTool – injectDoc', () => {
	it('Branch A: skips write when file does not exist', () => {
		const { tool, mockFs } = makeTool({ existsResult: false });
		const updatedFiles: string[] = [];
		(tool as any).injectDoc(
			'/not/existing/path.md',
			'content',
			updatedFiles
		);
		expect(mockFs.writeFileSync).not.toHaveBeenCalled();
		expect(updatedFiles).toHaveLength(0);
	});

	it('Branch B: appends marker+content when no marker in file', () => {
		const existingContent = '# Existing docs\n\nSome intro text.';
		const { tool, mockFs } = makeTool({
			existsResult: true,
			readResult: existingContent,
		});
		const updatedFiles: string[] = [];
		(tool as any).injectDoc(
			'/docs/page.md',
			'\n\n## `my_tool`\n\nDesc.\n\n',
			updatedFiles
		);
		expect(mockFs.writeFileSync).toHaveBeenCalledTimes(1);
		const written = (
			mockFs.writeFileSync.mock.calls[0] as unknown[]
		)?.[1] as string;
		expect(written).toContain('# Existing docs');
		expect(written).toContain('<!-- TOOLS-START -->');
		expect(written).toContain('## `my_tool`');
		expect(updatedFiles).toContain('/docs/page.md');
	});

	it('Branch C: replaces post-marker content when marker is present', () => {
		const MARKER = '<!-- TOOLS-START -->';
		const existingContent = `# Reference\n\nIntro text.\n${MARKER}\n## \`old_tool\`\n\nOld description.\n`;
		const { tool, mockFs } = makeTool({
			existsResult: true,
			readResult: existingContent,
		});
		const updatedFiles: string[] = [];
		(tool as any).injectDoc(
			'/docs/tools.md',
			'\n\n## `new_tool`\n\nNew description.\n\n',
			updatedFiles
		);
		expect(mockFs.writeFileSync).toHaveBeenCalledTimes(1);
		const written = (
			mockFs.writeFileSync.mock.calls[0] as unknown[]
		)?.[1] as string;
		expect(written).toContain('# Reference');
		expect(written).toContain(MARKER);
		expect(written).toContain('new_tool');
		expect(written).not.toContain('old_tool');
		expect(updatedFiles).toContain('/docs/tools.md');
	});
});
