import { z } from 'zod';
import { QAbstractTool } from '../abstract-tool';
import * as fs from 'fs';
import { resolve as pathResolve, dirname } from 'path';

/**
 * Tool to synchronize documentation content with code.
 * Automatically updates:
 * - Public Tools reference
 * - Internal Tools reference
 * - Transformers reference
 */
export class QSyncDocsTool extends QAbstractTool<z.ZodObject<{}>> {
	name = 'update_docs_content';
	description =
		'Auto-generate documentation files for Tools and Transformers based on current code.';
	schema = z.object({});

	protected _fs = fs;

	async execute(): Promise<{ summary: string; updatedFiles: string[] }> {
		const updatedFiles: string[] = [];
		const cwd = process.cwd();

		// 1. Get Tools via dynamic import to avoid circular dependency
		// Note: We assume the server exports QMcpServer class
		const { QMcpServer } = await import('../../server');
		const tools = QMcpServer.getDefaultTools();

		// Separate Public vs Internal
		// Heuristic: Internal tools usually are in internal-tools.ts or have names like 'check_', 'generate_test', 'update_docs'
		// We can categorize by checking if they are instance of classes in this file, but that's hard dynamically.
		// Better heuristic: internal tools start with 'check_', 'generate_test', 'update_', 'get_coverage'
		// Or simply hardcode the list or check descriptions?
		// Let's use a "public" vs "internal" classification based on names for now, or assume all in public-tools.ts are public.
		// Since we have instances, we can check their class names? No, minification might break it.
		// Let's use the names.
		const internalPrefixes = [
			'check_',
			'update_',
			'generate_test',
			'get_coverage',
			'scaffold_',
			'benchmark_',
		];
		const internalTools = tools.filter((t: any) =>
			internalPrefixes.some((p) => t.name.startsWith(p))
		);
		const publicTools = tools.filter(
			(t: any) => !internalPrefixes.some((p) => t.name.startsWith(p))
		);

		// 2. Generate Tools Documentation
		const publicDocs = this.generateToolMd(publicTools, 'Public MCP Tools');
		const internalDocs = this.generateToolMd(
			internalTools,
			'Internal MCP Tools'
		);

		this.writeDoc(
			pathResolve(cwd, 'docs-vitepress/en/mcp/public/tools.md'),
			publicDocs,
			updatedFiles
		);
		this.writeDoc(
			pathResolve(cwd, 'docs-vitepress/en/mcp/internal/tools.md'),
			internalDocs,
			updatedFiles
		);

		// 3. Generate Transformers Documentation
		const { TransformerLookupService } =
			await import('../../../core/services/transformer-lookup.service');
		const transformers =
			new TransformerLookupService().getAvailableTransformers();
		const transformerDocs = this.generateTransformerMd(transformers);

		this.writeDoc(
			pathResolve(cwd, 'docs-vitepress/en/guide/transformers.md'),
			transformerDocs,
			updatedFiles
		);

		return {
			summary: `Successfully updated ${updatedFiles.length} documentation files.`,
			updatedFiles,
		};
	}

	private generateToolMd(tools: any[], title: string): string {
		let md = `# ${title}\n\n`;
		md += `_Auto-generated by QSyncDocsTool. Do not edit manually._\n\n`;

		for (const tool of tools) {
			md += `## \`${tool.name}\`\n\n`;
			md += `${tool.description}\n\n`;
			md += `### Input Schema\n\n`;
			md += `\`\`\`json\n`;
			// format zod schema if possible?
			// tool.schema is a ZodObject. We can use zod-to-json-schema if installed, or just simple introspection
			// For now, let's just describe it or omit strict JSON schema to avoid huge deps if not needed.
			// Let's try to print a simplified view.
			const shape = tool.schema.shape || {};
			const simpleSchema: any = {};
			for (const key in shape) {
				const def = shape[key];
				simpleSchema[key] = {
					type: def._def.typeName,
					description: def.description,
				};
				if (def.isOptional && def.isOptional()) {
					simpleSchema[key].optional = true;
				}
			}
			md += JSON.stringify(simpleSchema, null, 2);
			md += `\n\`\`\`\n\n`;
		}
		return md;
	}

	private generateTransformerMd(transformers: string[]): string {
		let md = `# Built-in Transformers\n\n`;
		md += `QuickModel comes with a set of built-in transformers to handle common data types.\n\n`;
		md += `_Auto-generated by QSyncDocsTool._\n\n`;

		md += `| Transformer | Description |\n`;
		md += `| :--- | :--- |\n`;

		for (const t of transformers.sort()) {
			// We don't have descriptions in the registry yet, so just list them
			md += `| \`${t}\` | Handles \`${t}\` data types. |\n`;
		}

		md += `\n\nSee [Custom Transformers](./custom-transformers.md) to add your own.\n`;
		return md;
	}

	private writeDoc(path: string, content: string, updatedFiles: string[]) {
		// Ensure dir exists
		this._fs.mkdirSync(dirname(path), { recursive: true });
		this._fs.writeFileSync(path, content);
		updatedFiles.push(path);
	}
}
